volumes:
  #create prometheus volume
  prometheus-data:
  mc:

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      CF_SERVER_MOD: BMC4_FORGE_1.20.1_Server_Pack_v26.zip
      INIT_MEMORY: 512M
      MAX_MEMORY: 2G
      MOTD: chat(modded)
      TYPE: CURSEFORGE
      USE_AIKAR_FLAGS: "TRUE"
      VERSION: 1.20.1

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./mc:/data

  mc-monitor:
    image: itzg/mc-monitor
    container_name: mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    depends_on:
      - mc

  mc-prometheus:
    image: prom/prometheus:latest
    container_name: mc-prometheus
    restart: unless-stopped
    depends_on:
      - mc-monitor

    #link volumes and config
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
